Useful commands that were missing
MelanX/SkyblockBuilder pull request #7
Opened 2021-03-12 17:15 UTC by mcNETDev

Hi, I like the mod very well! unfortunately I missed a few commands. Instead of creating an issue, I briefly added it myself.
If you have any questions just ask.

I would like to add more commands and config options later on. But first I want to ask what you think of it.

Commands I would like to add:
/skyblock team setspawn (set the island spawn point)
/skyblock visit <team> (can only go if someone from the other team is online, everyone in the team receives a message and can then click on YES or NO in the chat)
/skyblock team info (gives information about the team, players etc.)
/skyblock team chat <message> (sends a message to team members only)
/sc <message> (-> /skyblock team chat)

Config options:
dropInventoryOnLeaveTeam
allowVisits

and maybe an internal Admin role in a team. Team creator -> Team Admin
He can then execute further commands
/skyblock team addAdmin <PlayerInTeam>
/skyblock team removeAdmin <Player>
/skyblock team disableVisit
/skyblock team enableVisit
/skyblock team kick <Player>
/skyblock team invite <Player>
/skyblock team accept <Player>
/skyblock team reject <Player>
/skyblock team setspawn
/skyblock team rename <newname>

Maybe we can also see if we are using a few features with FTB teams, chunks.

There are definitely more things that can be added later.
I am also ready to add these things myself, if you have no time.

2021-03-12 21:21 UTC, MelanX requested changes
Hi, thanks for putting that much effort to this mod. In my opinion you have a lot of good ideas.
As you can see, I request a few changes before merging it. I don't know but I think I put a suggestion for each change :D so you could simply commit these suggestions.

Now to your suggestions
- [x] <-- means it's cool, I would add it
- [ ] <-- means: read reason why not

Commands I would like to add:
- [x] /skyblock team setspawn (set the island spawn point)
- [x] /skyblock visit (can only go if someone from the other team is online, everyone in the team receives a message and can then click on YES or NO in the chat)
- [ ] /skyblock team info (gives information about the team, players etc.) --> already exists with /skyblock list <team> (maybe you could provide more information why it should be added)
- [x] /skyblock team chat (sends a message to team members only)
- [x] /sc (-> /skyblock team chat)

Config options:
- [x] dropInventoryOnLeaveTeam
- [x] allowVisits
- [ ] islandDistance = 8000 --> difficult. The distance is set because it's a good distance for biomes. Each team has the same biomes in the same order. Smaller and it would be a bit difficult and less biomes could be provided for each team. The nether size would decrease, too. 

- [ ] and maybe an internal Admin role in a team. Team creator -> Team Admin --> https://github.com/MelanX/SkyblockBuilder/commit/46c383bdeac703fd8acd66ef8a360ae7c51c03e9 --> it's too hard to maintain it with empty teams and other stuff in my opinion. Maybe you have a good solution, I don't have
For the following commands (which are meant to be used by the admin) I need to find a solution how to implement it without users can abuse it.
- [ ] /skyblock team addAdmin --> because at the moment i don't want admin(s)
- [ ] /skyblock team removeAdmin --> because at the moment i don't want admin(s)
- [x] /skyblock team disableVisit
- [x] /skyblock team enableVisit
- [x] /skyblock team kick
- [x] /skyblock team invite
- [x] /skyblock team accept
- [x] /skyblock team reject
- [x] /skyblock team setspawn
- [x] /skyblock team rename

That was everything from you. I hope you can work with that :)

2021-03-12 21:21 UTC, MelanX commented on src/main/java/de/melanx/skyblockbuilder/commands/HomeCommand.java
> +        return 1;
You should get the team and check if it's null. If yes, return 0. If no, continue with teleporting. 
```suggestion
        Team team = data.getTeamFromPlayer(player);
        if (team == null) {
            source.sendFeedback(new StringTextComponent("You currently in no team!").mergeStyle(TextFormatting.RED), false);
            return 0;
        }

        WorldUtil.teleportToIsland(player, data.getTeamFromPlayer(player).getIsland());
        return 1;
```

2021-03-12 21:21 UTC, MelanX commented on src/main/java/de/melanx/skyblockbuilder/commands/TeamCommand.java
> -        Team team = data.createTeam(name);
This can stay, then we need no `else`

2021-03-12 21:21 UTC, MelanX commented on src/main/java/de/melanx/skyblockbuilder/commands/TeamCommand.java
> +                    return 1;
This is like an error, you should return 0 and it should be red. 
```suggestion
                    source.sendFeedback(new StringTextComponent("You are already in a team, to create a new one you have to leave your team first!").mergeStyle(TextFormatting.RED), false);
                    return 0;
```

2021-03-12 21:21 UTC, MelanX commented on src/main/java/de/melanx/skyblockbuilder/EventListener.java
> +                .then(CreateCommand.register())
Sorry, I'm a bit strange. Should be sorted alphabetically. 
```suggestion
                .then(CreateCommand.register())
                .then(HomeCommand.register())
                .then(InviteCommand.register())
                .then(LeaveCommand.register())
                .then(ListCommand.register())
                .then(TeamCommand.register())
```

2021-03-12 21:21 UTC, MelanX commented on src/main/java/de/melanx/skyblockbuilder/commands/CreateCommand.java
> +
I'm not sure if I really want to add this. Maybe I would add a config for that. But I do have changes for this. Just look at my suggestion :) I mainly don't want to cast the player if it's not a player. I think that would cause issues with command blocks. *maybe it's not meant to used in command blocks, idk*

```suggestion
    public static ArgumentBuilder<CommandSource, ?> register() {
        return Commands.literal("create")
                .executes(context -> create(context.getSource(), NameGenerator.randomName(new Random()), Collections.emptyList()))
                .then(Commands.argument("name", StringArgumentType.word())
                        .executes(context -> create(context.getSource(), StringArgumentType.getString(context, "name"), Collections.emptyList()))
                        .then(Commands.argument("players", EntityArgument.players())
                                .requires(commandSource -> commandSource.hasPermissionLevel(2))
                                .executes(context -> create(context.getSource(), StringArgumentType.getString(context, "name"), EntityArgument.getPlayers(context, "players")))));
    }


    private static int create(CommandSource source, String name, Collection<ServerPlayerEntity> players) {
        ServerWorld world = source.getWorld();
        SkyblockSavedData data = SkyblockSavedData.get(world);

        if (data.teamExists(name)) {
            source.sendFeedback(new StringTextComponent(String.format("Team %s already exists! Please choose another name!", name)).mergeStyle(TextFormatting.RED), true);
            return 0;
        }

        Team team = data.createTeam(name);

        if (players.isEmpty() && source.getEntity() instanceof ServerPlayerEntity) {
            ServerPlayerEntity player = (ServerPlayerEntity) source.getEntity();
            team.addPlayer(player);
            WorldUtil.teleportToIsland(player, team.getIsland());
        } else {
            players.forEach(player -> {
                if (data.getTeamFromPlayer(player) != null) {
                    source.sendFeedback(new StringTextComponent(String.format("%s is already in a team, it can not be added!", player.getDisplayName().getString())).mergeStyle(TextFormatting.RED), false);
                } else {
                    team.addPlayer(player);
                    WorldUtil.teleportToIsland(player, team.getIsland());
                }
            });
        }
```

2021-03-12 21:24 UTC, MelanX commented
idk why my comment looks so very ugly at some point

2021-03-13 06:40 UTC, mcNETDev commented on src/main/java/de/melanx/skyblockbuilder/commands/TeamCommand.java
> -        Team team = data.createTeam(name);
done

2021-03-13 06:44 UTC, mcNETDev commented
hi, thank you for your detailed answer! I didn't expect that. I think your changes are good! I'll take care of the other things as soon as possible.

2021-03-13 13:04 UTC, merged